spring:
  application:
    name: consumer-message
server:
  port: 9600

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka/